// src/components/settings/StatisticsTab.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { ValidationError } from 'yup'

import { useMe, usesSettingsStatistics } from '@/hooks/auth-hooks.ts'
import { onboardingSchema } from '@/validations/onboarding.ts'
import { CURRENCIES } from '@/constants/currencies.ts'

import KitSettingsFieldWrapper from '@/components/kit/KitSettingsFieldWrapper.vue'
import KitDropdown from '@/components/kit/KitDropdown.vue'
import KitInput from '@/components/kit/KitInput.vue'
import KitButton from '@/components/kit/KitButton.vue'

const { me, refreshMe } = useMe()
const { settingsStatistics } = usesSettingsStatistics()

const currency = ref(me.value?.me.currency || '')
const monthStartDay = ref(me.value?.me.monthStartDay || '')
const monthlyBudget = ref(me.value?.me.monthlyBudget || '')

const errors = ref<Record<string, string>>({})

const validateForm = async () => {
  try {
    await onboardingSchema.validate(
      {
        currency: currency.value,
        monthlyBudget: Number(monthlyBudget.value),
        monthStartDay: Number(monthStartDay.value),
      },
      { abortEarly: false },
    )
    errors.value = {}
    return true
    // eslint-disable-next-line
  } catch (validationErrors: any) {
    errors.value = (validationErrors as ValidationError).inner.reduce(
      // eslint-disable-next-line
      (acc: Record<string, string>, error: any) => {
        if (!acc[error.path]) acc[error.path] = error.message
        return acc
      },
      {},
    )
    return false
  }
}

const update = async () => {
  console.log('update')
  try {
    const isValid = await validateForm()
    if (!isValid) return
    console.log('update.valid', currency.value, monthStartDay.value, monthlyBudget.value)

    const data = await settingsStatistics({
      currency: currency.value,
      monthStartDay: Number(monthStartDay.value),
      monthlyBudget: Number(monthlyBudget.value),
    })

    if (data) {
      refreshMe()
      console.log('settings.success', data)
      // toast.success($_('settings.success')) // TODO: add toast
    }

    // eslint-disable-next-line
  } catch (e: any) {
    try {
      const errorCodes = e.cause.extensions.originalError.errorCodes
      if (errorCodes) {
        errors.value = errorCodes
      }
      // eslint-disable-next-line
    } catch (e: any) {
      // toast.error($_('common_errors.server_error')) // TODO: add toast
    }
  }
}

const isChanged = computed(() => {
  return (
    currency.value !== me.value?.me.currency ||
    monthStartDay.value !== me.value?.me.monthStartDay ||
    monthlyBudget.value !== me.value?.me.monthlyBudget
  )
})
</script>

<template>
  <form @submit.prevent="update" class="form">
    <kit-settings-field-wrapper
      :label="$t('settings.fields.currency.label')"
      :description="$t('settings.fields.currency.description')"
      :error="Boolean(errors?.currency)"
      :message="errors?.currency ? $t(`settings.fields.currency.errors.${errors.currency}`) : ''"
    >
      <kit-dropdown
        :options="CURRENCIES"
        :placeholder="$t('settings.fields.currency.placeholder')"
        v-model="currency"
      />
    </kit-settings-field-wrapper>
    <kit-settings-field-wrapper
      :label="$t('settings.fields.monthStartDay.label')"
      :description="$t('settings.fields.monthStartDay.description')"
      :error="Boolean(errors?.monthStartDay)"
      :message="
        errors?.monthStartDay
          ? $t(`settings.fields.monthStartDay.errors.${errors.monthStartDay}`)
          : ''
      "
    >
      <kit-input
        v-model="monthStartDay"
        type="number"
        :placeholder="$t('settings.fields.monthStartDay.placeholder')"
        :error="Boolean(errors?.monthStartDay)"
      />
    </kit-settings-field-wrapper>
    <kit-settings-field-wrapper
      :label="$t('settings.fields.monthlyBudget.label')"
      :description="$t('settings.fields.monthlyBudget.description')"
      :error="Boolean(errors?.monthlyBudget)"
      :message="
        errors?.monthlyBudget
          ? $t(`settings.fields.monthlyBudget.errors.${errors.monthlyBudget}`)
          : ''
      "
    >
      <kit-input
        v-model="monthlyBudget"
        type="number"
        :placeholder="$t('settings.fields.monthlyBudget.placeholder')"
        :error="Boolean(errors?.monthlyBudget)"
      />
    </kit-settings-field-wrapper>
    <div class="buttons">
      <kit-button type="submit" :disabled="!isChanged">{{ $t('settings.submit') }}</kit-button>
    </div>
  </form>
</template>

<style scoped>
.form :deep(.texts),
.form :deep(.control) {
  padding-inline: var(--spacing-2xl);
}

.buttons {
  display: flex;
  justify-content: flex-end;
  gap: var(--spacing-lg);
  padding: var(--spacing-xl);

  border-top: 1px solid var(--border-secondary);
}

@media screen and (min-width: 768px) {
  .form :deep(.texts) {
    padding-inline: var(--spacing-2xl) 0;
  }
  .form :deep(.control) {
    padding-inline: 0 var(--spacing-2xl);
  }

  .buttons {
    padding: var(--spacing-2xl);
  }
}
</style>

// src/lib/components/settings/StatisticsTab.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { ValidationError } from 'yup';
	import { _ } from 'svelte-i18n';

	import { me } from '$lib/store/me';
	import SettingsFieldWrapper from '$lib/kit/SettingsFieldWrapper.svelte';
	import Input from '$lib/kit/Input.svelte';
	import Dropdown from '$lib/kit/Dropdown.svelte';
	import Button from '$lib/kit/Button.svelte';
	import { CURRENCIES } from '$lib/constants/currencies';
	import { onboardingSchema } from '$lib/validations/onboarding';
	import AuthService from '$lib/services/auth-service';
	import toast from 'svelte-french-toast';

	let currency = $me?.currency || CURRENCIES[0];
	let monthStartDay = $me?.monthStartDay || 1;
	let monthlyBudget = $me?.monthlyBudget || 0;

	let errors: Record<string, string> = {};

	const validateForm = async () => {
		try {
			await onboardingSchema.validate(
				{ currency, monthlyBudget, monthStartDay },
				{ abortEarly: false }
			);
			errors = {};
			return true;
			// eslint-disable-next-line
		} catch (validationErrors: any) {
			errors = (validationErrors as ValidationError).inner.reduce(
				// eslint-disable-next-line
				(acc: Record<string, string>, error: any) => {
					if (!acc[error.path]) acc[error.path] = error.message;
					return acc;
				},
				{}
			);
			return false;
		}
	};

	const update = async () => {
		try {
			const isValid = await validateForm();
			if (!isValid) return;

			const data = await AuthService.settingsStatistics({ currency, monthStartDay, monthlyBudget });

			if (data) {
				me.set(data);
				toast.success($_('settings.success'));
			}

			// eslint-disable-next-line
		} catch (e: any) {
			try {
				const errorCodes = e.cause.extensions.originalError.errorCodes;
				if (errorCodes) {
					errors = errorCodes;
				}
				// eslint-disable-next-line
			} catch (e: any) {
				toast.error($_('common_errors.server_error'));
			}
		}
	};

	$: isChanged =
		currency !== $me?.currency ||
		monthStartDay !== $me?.monthStartDay ||
		monthlyBudget !== $me?.monthlyBudget;
</script>

<form on:submit|preventDefault={update} class="form">
	<SettingsFieldWrapper
		label={$_('settings.fields.currency.label')}
		description={$_('settings.fields.currency.description')}
		error={Boolean(errors?.currency)}
		message={errors?.currency ? $_(`settings.fields.currency.errors.${errors.currency}`) : ''}
	>
		<Dropdown
			options={CURRENCIES}
			placeholder={$_('settings.fields.currency.placeholder')}
			bind:selected={currency}
		/>
	</SettingsFieldWrapper>
	<SettingsFieldWrapper
		label={$_('settings.fields.monthStartDay.label')}
		description={$_('settings.fields.monthStartDay.description')}
		error={Boolean(errors?.monthStartDay)}
		message={errors?.monthStartDay
			? $_(`settings.fields.monthStartDay.errors.${errors.monthStartDay}`)
			: ''}
	>
		<Input
			bind:value={monthStartDay}
			type="number"
			placeholder={$_('settings.fields.monthStartDay.placeholder')}
			error={Boolean(errors?.monthStartDay)}
		/>
	</SettingsFieldWrapper>
	<SettingsFieldWrapper
		label={$_('settings.fields.monthlyBudget.label')}
		description={$_('settings.fields.monthlyBudget.description')}
		error={Boolean(errors?.monthlyBudget)}
		message={errors?.monthlyBudget
			? $_(`settings.fields.monthlyBudget.errors.${errors.monthlyBudget}`)
			: ''}
	>
		<Input
			bind:value={monthlyBudget}
			type="number"
			placeholder={$_('settings.fields.monthlyBudget.placeholder')}
			error={Boolean(errors?.monthlyBudget)}
		/>
	</SettingsFieldWrapper>
	<div class="buttons">
		<Button type="submit" disabled={!isChanged}>{$_('settings.submit')}</Button>
	</div>
</form>

<style>
	.form :global(.texts),
	.form :global(.control) {
		padding-inline: var(--spacing-2xl);
	}

	.buttons {
		display: flex;
		justify-content: flex-end;
		gap: var(--spacing-lg);
		padding: var(--spacing-xl);

		border-top: 1px solid var(--border-secondary);
	}

	@media screen and (min-width: 768px) {
		.form :global(.texts) {
			padding-inline: var(--spacing-2xl) 0;
		}
		.form :global(.control) {
			padding-inline: 0 var(--spacing-2xl);
		}

		.buttons {
			padding: var(--spacing-2xl);
		}
	}
</style>
