// src/components/LangSwitcher.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useI18n } from 'vue-i18n'

import KitDropdown from '@/components/kit/KitDropdown.vue'

const { locale, availableLocales } = useI18n()

const getLangLabel = (locale: string) => {
  if (locale === 'en') return 'Eng'
  if (locale === 'uk-UA') return 'Укр'
  return 'locale'
}

onMounted(() => {
  const navigatorLang = window.navigator.language
  if (navigatorLang === 'en' || navigatorLang === 'uk-UA') {
    locale.value = navigatorLang
  } else locale.value = 'en'
})
</script>

<template>
  <kit-dropdown
    v-model="locale"
    :options="availableLocales"
    :getOptionLabel="getLangLabel"
    placeholder="Select language"
  />
</template>

// src/lib/components/LangSwitcher.svelte
<script lang="ts">
	import { locale, locales } from 'svelte-i18n';
	import Dropdown from '$lib/kit/Dropdown.svelte';

	const getLangLabel = (locale: string) => {
		switch (locale) {
			case 'en':
				return 'Eng';
			case 'uk-UA':
				return 'Укр';
			default:
				return locale;
		}
	};
</script>

<Dropdown bind:selected={$locale} options={$locales} getOptionLabel={getLangLabel} />
